use rand's SmallRng for random number generation
Stebalien/tempfile pull request #141
Opened 2021-03-24 17:50 UTC by mcginty

#119 seems to have not been updated, so here's another take at it, trying to keep the diff as small as possible.

This approach stores a `SmallRng` as a thread-local variable, basically [directly copying the way `rand` does its own `thread_rng()`](https://github.com/rust-random/rand/blob/master/src/rngs/thread.rs) so as to avoid any issues or incompatibilities.

I opted not to further change the way that the `OsString` is built since that feels like it may be better in another PR.

2021-03-25 19:42 UTC, Stebalien requested changes
One small nit, but otherwise LGTM.

2021-03-25 19:42 UTC, Stebalien commented on src/util.rs
> +    static THREAD_RNG_KEY: Rc<UnsafeCell<SmallRng>> = Rc::new(UnsafeCell::new(SmallRng::from_entropy()));
We can drop the Rc, right? Just use `THREAD_RNG_KEY.with(|rng| use rng...)`.

2021-04-09 18:45 UTC, Stebalien approved these changes

2021-04-09 18:45 UTC, merged

2021-04-10 06:16 UTC, mcginty commented
@Stebalien sorry I totally spaced on getting those changes in, thanks so much for merging!